# pandas 기초

### 주요 내용

1. csv, xlsx 파일 불러오기
2. 데이터 살펴보기
3. DRM 보안 파일 불러오기

<br>

### 목표 
1. 분석에 필요한 데이터를 python으로 불러올 수 있다.
2. 데이터의 일부나 특성을 확인할 수 있다. 


<br>
<hr>
<br>

## 1. 파일 불러와서 살펴보기

**pandas** 라이브러리의 *read_csv()* 등의 함수를 활용해서 데이터 불러오기 가능 
아래의 표현들을 활용해서 데이터 파일의 경로 지정 필요 

* `/` : **root**. Windows에서는 C:\
* `~/` : 사용자 폴더. Windows에서는 C:\Users\사용자계정이름
* `./` : 현재 작업 폴더(working directory), 별도로 작업하지 않은 경우 생략 가능
* `../` : 현재 폴더의 상위 폴더


`바탕화면`처럼 익숙한 곳에 새로운 폴더를 만들고, 데이터 파일을 옮겨서 작업하는 것을 추천

In [1]:
# 현재 작업 폴더 확인
    ## print working directory
%pwd

'C:\\Users\\jhpark\\Desktop\\강의자료_Python데이터전처리\\Python실습'

In [ ]:
# 경로 지정 실습
"./data/insurance.csv"

<br>

### 1.1. CSV 파일 불러오기

**pandas** 라이브러리 불러오기

In [2]:
import pandas as pd

In [3]:
# pandas의 read_csv( ) 활용
df_ins= pd.read_csv("./data/insurance.csv")
df_ins= pd.read_csv("data/insurance.csv")
df_ins    
    ## 경로가 중요! 
    ## ./ : ipynb 노트북 파일 폴더
    ## ./ 생략 가능
    ## Tab으로 자동 완성 기능 활용 가능

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
# 타입 확인
type(df_ins)
    ## "DataFrame"

pandas.core.frame.DataFrame

In [ ]:
# 메서드의 확인(마침표 뒤에서 Tab 누르기)
df_ins.

<br>

### 1.2. 데이터 살펴보기

In [7]:
# head( )로 앞 몇개 관측치 확인
df_ins.head(n=10)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [8]:
# tail( )로 끝 몇 개 관측치 확인
df_ins.tail(n=3)

      age     sex    bmi  children smoker     region     charges
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [9]:
# 관측치/ 변수 개수 확인
df_ins.shape

(1338, 7)

In [11]:
# 관측치 개수만 확인
df_ins.shape[1]

7

In [12]:
# index(행 이름) 확인
df_ins.index

RangeIndex(start=0, stop=1338, step=1)

In [13]:
# columns(변수 이름) 확인
df_ins.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [14]:
# 변수 형식 확인
df_ins.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

<br>

#### [실습] data 폴더의 PulseRates.csv를 불러와서 df_pr로 저장하기

이후 자유롭게 데이터 탐색하기

In [17]:
df_pr = pd.read_csv("./data/PulseRates.csv")
df_pr

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93
...,...,...,...,...,...,...,...,...,...,...,...
105,93,27.0,19,2,2,2,3,2,119.0,120.0,98
106,161,43.0,19,2,2,2,3,2,90.0,89.0,98
107,182,60.0,22,1,2,1,3,2,86.0,84.0,98
108,170,65.0,18,1,2,1,1,2,69.0,64.0,98
109,185,85.0,19,1,2,1,2,2,75.0,68.0,98

In [19]:
df_pr.dtypes

Height        int64
Weight      float64
Age           int64
Gender        int64
Smokes        int64
Alcohol       int64
Exercise      int64
Ran           int64
Pulse1      float64
Pulse2      float64
Year          int64
dtype: object

#### [참고] Encoding 지정 및 index, header 지정

In [20]:
# 인코딩(글자 저장 방법) 오류 발생
    ## UnicodeDecodeError  'utf-8' codec can't decode byte 0xbc in position 1: invalid start byte
pd.read_csv('data/고용지표_20221115084415.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 1: invalid start byte

In [21]:
# 옵션 encoding='CP949' 추가
pd.read_csv('data/고용지표_20221115084415.csv', encoding='CP949')

,성별(1),2021. 08,2021. 08.1,2021. 08.2,2021. 09,2021. 09.1,2021. 09.2,2021. 10,2021. 10.1,2021. 10.2,...,2022. 04.2,2022. 05,2022. 05.1,2022. 05.2,2022. 06,2022. 06.1,2022. 06.2,2022. 07,2022. 07.1,2022. 07.2
0,성별(1),경제활동참가율,실업률,고용률,경제활동참가율,실업률,고용률,경제활동참가율,실업률,고용률,...,고용률,경제활동참가율,실업률,고용률,경제활동참가율,실업률,고용률,경제활동참가율,실업률,고용률
1,합계,61.7,4.0,59.2,61.9,3.6,59.7,62.1,4.2,59.5,...,60.4,63.0,3.5,60.8,63.0,3.4,60.8,62.9,3.3,60.9
2,남자,70.0,4.1,67.1,70.3,3.8,67.7,70.6,4.6,67.3,...,68.7,71.8,3.7,69.2,71.6,3.3,69.2,71.3,3.4,68.9
3,여자,54.2,3.9,52.1,54.3,3.4,52.5,54.5,3.7,52.5,...,52.9,55.0,3.3,53.2,55.2,3.6,53.2,55.4,3.1,53

In [22]:
# index, header 지정
pd.read_csv('data/고용지표_20221115084415.csv', encoding='CP949', index_col=0, header=[0,1])

성별(1) 2021. 08            2021. 09            2021. 10            2021. 11  \
성별(1)  경제활동참가율  실업률   고용률  경제활동참가율  실업률   고용률  경제활동참가율  실업률   고용률  경제활동참가율
합계        61.7  4.0  59.2     61.9  3.6  59.7     62.1  4.2  59.5     62.5
남자        70.0  4.1  67.1     70.3  3.8  67.7     70.6  4.6  67.3     71.2
여자        54.2  3.9  52.1     54.3  3.4  52.5     54.5  3.7  52.5     54.6

성별(1)  ... 2022. 04 2022. 05            2022. 06            2022. 07       \
성별(1)  ...      고용률  경제활동참가율  실업률   고용률  경제활동참가율  실업률   고용률  경제활동참가율  실업률
합계     ...     60.4     63.0  3.5  60.8     63.0  3.4  60.8     62.9  3.3
남자     ...     68.7     71.8  3.7  69.2     71.6  3.3  69.2     71.3  3.4
여자     ...     52.9     55.0  3.3  53.2     55.2  3.6  53.2     55.4  3.1

성별(1)
성별(1)   고용률
합계     60.9
남자     68.9
여자     53.0

[3 rows x 36 columns]

<br>


### 1.3. Excel 파일 불러오기  

`Excel` 파일은 구버전의 **xls**와 새로운 버전의 **xlsx**로 구분하며 추가 라이브러리 `xlrd`와 `openpyxl` 설치 필수
 이후 pandas의 `read_excel( )`을 사용 가능

In [23]:
# 무난한 첫번째 시트 데이터 불러오기
sheet1 = pd.read_excel('./data/test.xlsx')
sheet1

   ID  Var1  Var2  Var3
0   1    11    45    75
1   2    54    32    34
2   4    65    43    54

In [24]:
# 시트 번호 지정하고 2줄 무시하기
sheet2 = pd.read_excel('data/test.xlsx', sheet_name=1, skiprows=2)
sheet2
    ## sheet_name : 시트 이름이나 번호 지정, 번호는 0부터 시작
    ## skiprows   : 무시할 행 수

   이름  나이    키
0  민서  20  160
1  민준  21  175

In [25]:
# 첫 행부터 데이터가 시작되는 데이터 불러오기
sheet3 = pd.read_excel('data/test.xlsx', sheet_name=2, header=None)
sheet3
    ## header : 첫 행에 변수이름이 저장되었는지 여부

      0   1
0  2015  32
1  2016  34
2  2017   -

In [26]:
# 첫 행부터 데이터가 시작되는 데이터 불러오면서 변수 이름 지정하기
sheet3 = pd.read_excel('data/test.xlsx', sheet_name=2, header=None, names=['년도','건수'])
sheet3

     년도  건수
0  2015  32
1  2016  34
2  2017   -

In [29]:
sheet3.dtypes

년도      int64
건수    float64
dtype: object

In [28]:
# 결측 저장값 지정하기
sheet3 = pd.read_excel('data/test.xlsx', sheet_name=2, header=None, names=['년도','건수'], na_values='-')
sheet3
    ## NaN : 결측값

     년도    건수
0  2015  32.0
1  2016  34.0
2  2017   NaN


<br>  

####  [실습] 아래의 사이트에서 관심있는 데이터를 탐색하기

* csv 파일 중 인코딩 관련 에러가 발생할 경우 read_csv( )안에서 `encoding='CP949'` 옵션 추가
* xlsx의 경우 다운로드한 파일을 열어서 읽기 전용을 해제해야 할 수도 있음



[공공데이터포털](https://www.data.go.kr/index.do)

[서울 열린데이터 광장](http://data.seoul.go.kr/)

[Dacon](https://dacon.io/)

In [34]:
pd.read_csv("/Users/jhpark/Downloads/한국국제협력단_국별 개발협력동향_20240110.csv", encoding="cp949")

,국가명,지역,사무소,구분,분야,제목,본문1,본문2,본문3,영문(title),영문(main1),영문(main2),영문(main3),출처,링크,날짜
0,가나,서아프리카,가나,수원국,거버넌스평화,"AfroFuture 재단과 UNICEF, 힘을 합치다",AfroFuture 재단과 UNICEF가 약속하고 있는 협력에서는 가나 어린이들의...,AfroFuture의 중요한 약속은 전국에 적어도 30개의 위생 시설을 짓는 데 자...,AfroFuture의 공동 창업자인 Ken Agyapong Jnr는 플랫폼의 영향력...,AfroFuture Foundation and UNICEF join forces,"In a promising collaboration, the AfroFuture F...",A significant commitment from AfroFuture invol...,"Ken Agyapong Jnr., co-founder of AfroFuture, e...",Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-24
1,가나,서아프리카,가나,수원국,성평등,석유 가치 사슬에서 독립된 성 평등 정책 도입 제안,"12월 23일, 웨스턴 주 타코라디에서 열린 석유 가치 사슬 관련 여성 대화에 참석...",이 대화는 WILAF 가나가 FON(Friends of Nation)과 협력하여 조...,"석유 및 가스 분야에 여성들의 적극적인 참여를 위한 사례로, Darko는 배 추적,...",Create stand-alone gender policy in petroleum ...,Participants at a women’s dialogue on the petr...,The dialogue was organisedby WiLDAF Ghana in c...,Making a case for women’s active participation...,Ghanaian Times,https://www.ghanaiantimes.com.gh/create-stand-...,2023-12-23
2,가나,서아프리카,가나,수원국,농촌개발,무기비료 대안: 청년들에게 퇴비 생산 체험,젊은이들을 위한 퇴비 생산 및 디지털 농업 서비스에 대한 역량 강화 프로그램이 As...,"62명의 참가자는 청년 단체, 젊은 농부 대표 및 고용이 미흡하거나 실직 상태인 다...",이번 연수는 농업이 청년층의 취업 기회를 확대할 수 있는 실질적인 잠재력을 갖춘 핵...,Alternative for inorganic fertilizer: Youth ex...,A capacity building programme to expose young ...,The 62 participants were from diverse group of...,The training takes place on the back of the fa...,Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-30
3,가나,서아프리카,가나,수원국,농촌개발,"Zipline, 돼지 농장에 인공 수정을 위한 돼지 정액 배송",항공물류 배송업체인 Zipline과 가나 돼지 농업을 발전시키는 축산 사업인 Pip...,콜드체인 인큐베이터에 보관된 돼지 정액은 정확한 낙하 능력을 가진 드론에 의해 운반...,Zipline의 계획은 농업에서 효율성과 생산량을 증가시키기 위해 기술이 사용되는 ...,Zipline to Deliver Swine Semen to Pig Farms fo...,"Zipline, an aerial logistics delivery company ...","The swine semen, stored in cold-chain incubato...",Zipline’s initiative is seen as a part of the ...,Ghanaian Times,https://www.ghanaiantimes.com.gh/zipline-to-de...,2023-12-21
4,가나,서아프리카,가나,KOICA,교육,"한국국제협력단(KOICA), 가나 교육청에 100만 달러 교수학습 지원",한국국제협력단(KOICA)은 화요일에 가나 교육청(GES)에 100만 달러 이상에...,"KOICA 가나 사무소 이동현 소장은 교육 자료를 제공하면서 ""여성 STEM 프로젝...",Nkansah박사는 학생 중 12.5%가 각종 고등학교에서 과학 프로그램을 추구할 ...,"KOICA presents $1m teaching, learning aid to GES",The Korean Inter­national Coop­eration Agency ...,"The Country Director of KO­ICA Ghana, Mr Dongh...",He said about 12.5 per cent of students were a...,Ghanaian Times,https://www.ghanaiantimes.com.gh/koica-present...,2023-12-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,필리핀,동남아시아,필리핀,수원국,교육,"독해, 수학, 과학에서 필리핀 학생들이 여전히 최하위권 성적을 기록 중 - OECD...",OECD 국제학생평가프로그램에 참여한 다른 국가 학생들에 비해 필리핀 학생들의 평균...,"188개 학교 출신의 필리핀 학생 7,193명은 수학에서 평균 355점을 기록했으며...",2018년의 평가에서 기록한 필리핀 학생들의 저조한 학업성적은 교육부로 하여금 필리...,PH students still among lowest scorers in read...,There was no significant improvement in the av...,"The 7,193 Filipino students from 188 schools s...",The dismal performance of the Philippines in t...,Inquirer.net,https://newsinfo.inquirer.net/1871182/ph-stude...,2023-12-06
705,필리핀,동남아시아,필리핀,수원국,농촌개발,"마르코스, 아세안에 10개년 식량 안보 로드맵 수립 촉구",전 날 마르코스 대통령은 동남아시아국가연합 (ASEAN)과 일본에 기후 행동 및 농...,"마르코스 대통령은 도쿄에서 열린 일본-아세안 특별정상회담 세 번째 세션에서 ""식량 ...","""지속 가능한 에너지 안보는 저탄소 지역을 실현하고 기후 변화에 대응하기 위한 청정...",Marcos urges ASEAN: Craft 10-year food securit...,President Marcos yesterday urged the Associati...,“Inasmuch as food security is one of my admini...,“Sustainable energy security is a twin priorit...,Philstar,https://www.philstar.com/headlines/2023/12/18/...,2023-12-18
706,필리핀,동남아시아,필리핀,수원국,거버넌스평화,"BARMM, 24년 예산으로 98.4-B를 승인하고 2023년 사용하지 않은 자금에...","방사모로 의회는 수요일에 만장일치로 내년도 예산 984억 페소를 승인했으며, 자치 ...","재정·예산·관리위원회는 모든 부처, 기관, 사무실의 예산 제안을 철저히 조사해 다양...","2024년 예산에서는 교육에 여전히 302억 페소, 인프라에 177억 페소, 건강에...","BARMM okays 98.4-B ’24 budget, rushes reso on ...",The Bangsamoro Parliament on Wednesday unanimo...,"It said the Committee on Finance, Budget, and ...",It said the 2024 budget would “still prioritiz...,Business Mirror,https://businessmirror.com.ph/2023/12/28/barmm...,2023-12-28
707,필리핀,동남아시아,필리핀,수원국,기타,"세계은행, 2023년 필리핀 GDP 성장률 전망치 5.6%로 유지","세계은행은 필리핀 경제가 3분기에 성장 반등을 보인 후, 가계 및 정부 소비가 4분...",관광 부문의 회복과 IT-BPO 산업의 지속적인 성과로 인해 서비스가 성장을 주도할...,중기적으로 국내 수요의 개선으로 2024-2025년 평균 5.8%의 완만한 성장률 ...,World Bank keeps PHL 5.6% GDP growth projectio...,THE World Bank kept its 5.6-percent growth pro...,“Services are expected to drive growth due to ...,"Over the medium term, the December 2023 Philip...",Business Mirror,https://businessmirror.com.ph/2023/12/06/world...,2023-12-06
708,필리핀,동남아시아,필리핀,국제기구,기후행동,"아시아개발은행(ABD), 필리핀의 기후복원력 및 저탄소 이니셔티브 강화를 위해 2억...",ADB는 인프라 준비 및 혁신 시설(IPIF)에 대한 두번째 추가 자금인 이 대출이...,IPIF는 필리핀 정부가 주력 프로젝트로 선정한 복잡하고 중요한 기후 회복력 있는 ...,필리핀의 인프라 개발에 대한 ADB의 지원은 2018년 이후 꾸준히 증가하여 현재 ...,ADB okays $200-M loan to boost PHL’s climate r...,"ADB said the loan, the second additional finan...",The IPIF is used to support the preparation of...,ADB’s support for infrastructure development i...,Business Mirror,https://businessmirror.com.ph/2023/12/09/adb-o...,2023-12-09

In [35]:
pd.read_csv("../../../Downloads/한국국제협력단_국별 개발협력동향_20240110.csv", encoding="cp949")

,국가명,지역,사무소,구분,분야,제목,본문1,본문2,본문3,영문(title),영문(main1),영문(main2),영문(main3),출처,링크,날짜
0,가나,서아프리카,가나,수원국,거버넌스평화,"AfroFuture 재단과 UNICEF, 힘을 합치다",AfroFuture 재단과 UNICEF가 약속하고 있는 협력에서는 가나 어린이들의...,AfroFuture의 중요한 약속은 전국에 적어도 30개의 위생 시설을 짓는 데 자...,AfroFuture의 공동 창업자인 Ken Agyapong Jnr는 플랫폼의 영향력...,AfroFuture Foundation and UNICEF join forces,"In a promising collaboration, the AfroFuture F...",A significant commitment from AfroFuture invol...,"Ken Agyapong Jnr., co-founder of AfroFuture, e...",Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-24
1,가나,서아프리카,가나,수원국,성평등,석유 가치 사슬에서 독립된 성 평등 정책 도입 제안,"12월 23일, 웨스턴 주 타코라디에서 열린 석유 가치 사슬 관련 여성 대화에 참석...",이 대화는 WILAF 가나가 FON(Friends of Nation)과 협력하여 조...,"석유 및 가스 분야에 여성들의 적극적인 참여를 위한 사례로, Darko는 배 추적,...",Create stand-alone gender policy in petroleum ...,Participants at a women’s dialogue on the petr...,The dialogue was organisedby WiLDAF Ghana in c...,Making a case for women’s active participation...,Ghanaian Times,https://www.ghanaiantimes.com.gh/create-stand-...,2023-12-23
2,가나,서아프리카,가나,수원국,농촌개발,무기비료 대안: 청년들에게 퇴비 생산 체험,젊은이들을 위한 퇴비 생산 및 디지털 농업 서비스에 대한 역량 강화 프로그램이 As...,"62명의 참가자는 청년 단체, 젊은 농부 대표 및 고용이 미흡하거나 실직 상태인 다...",이번 연수는 농업이 청년층의 취업 기회를 확대할 수 있는 실질적인 잠재력을 갖춘 핵...,Alternative for inorganic fertilizer: Youth ex...,A capacity building programme to expose young ...,The 62 participants were from diverse group of...,The training takes place on the back of the fa...,Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-30
3,가나,서아프리카,가나,수원국,농촌개발,"Zipline, 돼지 농장에 인공 수정을 위한 돼지 정액 배송",항공물류 배송업체인 Zipline과 가나 돼지 농업을 발전시키는 축산 사업인 Pip...,콜드체인 인큐베이터에 보관된 돼지 정액은 정확한 낙하 능력을 가진 드론에 의해 운반...,Zipline의 계획은 농업에서 효율성과 생산량을 증가시키기 위해 기술이 사용되는 ...,Zipline to Deliver Swine Semen to Pig Farms fo...,"Zipline, an aerial logistics delivery company ...","The swine semen, stored in cold-chain incubato...",Zipline’s initiative is seen as a part of the ...,Ghanaian Times,https://www.ghanaiantimes.com.gh/zipline-to-de...,2023-12-21
4,가나,서아프리카,가나,KOICA,교육,"한국국제협력단(KOICA), 가나 교육청에 100만 달러 교수학습 지원",한국국제협력단(KOICA)은 화요일에 가나 교육청(GES)에 100만 달러 이상에...,"KOICA 가나 사무소 이동현 소장은 교육 자료를 제공하면서 ""여성 STEM 프로젝...",Nkansah박사는 학생 중 12.5%가 각종 고등학교에서 과학 프로그램을 추구할 ...,"KOICA presents $1m teaching, learning aid to GES",The Korean Inter­national Coop­eration Agency ...,"The Country Director of KO­ICA Ghana, Mr Dongh...",He said about 12.5 per cent of students were a...,Ghanaian Times,https://www.ghanaiantimes.com.gh/koica-present...,2023-12-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,필리핀,동남아시아,필리핀,수원국,교육,"독해, 수학, 과학에서 필리핀 학생들이 여전히 최하위권 성적을 기록 중 - OECD...",OECD 국제학생평가프로그램에 참여한 다른 국가 학생들에 비해 필리핀 학생들의 평균...,"188개 학교 출신의 필리핀 학생 7,193명은 수학에서 평균 355점을 기록했으며...",2018년의 평가에서 기록한 필리핀 학생들의 저조한 학업성적은 교육부로 하여금 필리...,PH students still among lowest scorers in read...,There was no significant improvement in the av...,"The 7,193 Filipino students from 188 schools s...",The dismal performance of the Philippines in t...,Inquirer.net,https://newsinfo.inquirer.net/1871182/ph-stude...,2023-12-06
705,필리핀,동남아시아,필리핀,수원국,농촌개발,"마르코스, 아세안에 10개년 식량 안보 로드맵 수립 촉구",전 날 마르코스 대통령은 동남아시아국가연합 (ASEAN)과 일본에 기후 행동 및 농...,"마르코스 대통령은 도쿄에서 열린 일본-아세안 특별정상회담 세 번째 세션에서 ""식량 ...","""지속 가능한 에너지 안보는 저탄소 지역을 실현하고 기후 변화에 대응하기 위한 청정...",Marcos urges ASEAN: Craft 10-year food securit...,President Marcos yesterday urged the Associati...,“Inasmuch as food security is one of my admini...,“Sustainable energy security is a twin priorit...,Philstar,https://www.philstar.com/headlines/2023/12/18/...,2023-12-18
706,필리핀,동남아시아,필리핀,수원국,거버넌스평화,"BARMM, 24년 예산으로 98.4-B를 승인하고 2023년 사용하지 않은 자금에...","방사모로 의회는 수요일에 만장일치로 내년도 예산 984억 페소를 승인했으며, 자치 ...","재정·예산·관리위원회는 모든 부처, 기관, 사무실의 예산 제안을 철저히 조사해 다양...","2024년 예산에서는 교육에 여전히 302억 페소, 인프라에 177억 페소, 건강에...","BARMM okays 98.4-B ’24 budget, rushes reso on ...",The Bangsamoro Parliament on Wednesday unanimo...,"It said the Committee on Finance, Budget, and ...",It said the 2024 budget would “still prioritiz...,Business Mirror,https://businessmirror.com.ph/2023/12/28/barmm...,2023-12-28
707,필리핀,동남아시아,필리핀,수원국,기타,"세계은행, 2023년 필리핀 GDP 성장률 전망치 5.6%로 유지","세계은행은 필리핀 경제가 3분기에 성장 반등을 보인 후, 가계 및 정부 소비가 4분...",관광 부문의 회복과 IT-BPO 산업의 지속적인 성과로 인해 서비스가 성장을 주도할...,중기적으로 국내 수요의 개선으로 2024-2025년 평균 5.8%의 완만한 성장률 ...,World Bank keeps PHL 5.6% GDP growth projectio...,THE World Bank kept its 5.6-percent growth pro...,“Services are expected to drive growth due to ...,"Over the medium term, the December 2023 Philip...",Business Mirror,https://businessmirror.com.ph/2023/12/06/world...,2023-12-06
708,필리핀,동남아시아,필리핀,국제기구,기후행동,"아시아개발은행(ABD), 필리핀의 기후복원력 및 저탄소 이니셔티브 강화를 위해 2억...",ADB는 인프라 준비 및 혁신 시설(IPIF)에 대한 두번째 추가 자금인 이 대출이...,IPIF는 필리핀 정부가 주력 프로젝트로 선정한 복잡하고 중요한 기후 회복력 있는 ...,필리핀의 인프라 개발에 대한 ADB의 지원은 2018년 이후 꾸준히 증가하여 현재 ...,ADB okays $200-M loan to boost PHL’s climate r...,"ADB said the loan, the second additional finan...",The IPIF is used to support the preparation of...,ADB’s support for infrastructure development i...,Business Mirror,https://businessmirror.com.ph/2023/12/09/adb-o...,2023-12-09

In [37]:
pd.read_csv("data/한국국제협력단_국별 개발협력동향_20240110.csv", encoding="cp949")

FileNotFoundError: [Errno 2] No such file or directory: 'data/한국국제협력단_국별 개발협력동향_20240110.csv'

In [38]:
sheet1=pd.read_csv("../../../Downloads/한국국제협력단_국별 개발협력동향_20240110.csv",encoding="cp949")

In [39]:
sheet1

,국가명,지역,사무소,구분,분야,제목,본문1,본문2,본문3,영문(title),영문(main1),영문(main2),영문(main3),출처,링크,날짜
0,가나,서아프리카,가나,수원국,거버넌스평화,"AfroFuture 재단과 UNICEF, 힘을 합치다",AfroFuture 재단과 UNICEF가 약속하고 있는 협력에서는 가나 어린이들의...,AfroFuture의 중요한 약속은 전국에 적어도 30개의 위생 시설을 짓는 데 자...,AfroFuture의 공동 창업자인 Ken Agyapong Jnr는 플랫폼의 영향력...,AfroFuture Foundation and UNICEF join forces,"In a promising collaboration, the AfroFuture F...",A significant commitment from AfroFuture invol...,"Ken Agyapong Jnr., co-founder of AfroFuture, e...",Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-24
1,가나,서아프리카,가나,수원국,성평등,석유 가치 사슬에서 독립된 성 평등 정책 도입 제안,"12월 23일, 웨스턴 주 타코라디에서 열린 석유 가치 사슬 관련 여성 대화에 참석...",이 대화는 WILAF 가나가 FON(Friends of Nation)과 협력하여 조...,"석유 및 가스 분야에 여성들의 적극적인 참여를 위한 사례로, Darko는 배 추적,...",Create stand-alone gender policy in petroleum ...,Participants at a women’s dialogue on the petr...,The dialogue was organisedby WiLDAF Ghana in c...,Making a case for women’s active participation...,Ghanaian Times,https://www.ghanaiantimes.com.gh/create-stand-...,2023-12-23
2,가나,서아프리카,가나,수원국,농촌개발,무기비료 대안: 청년들에게 퇴비 생산 체험,젊은이들을 위한 퇴비 생산 및 디지털 농업 서비스에 대한 역량 강화 프로그램이 As...,"62명의 참가자는 청년 단체, 젊은 농부 대표 및 고용이 미흡하거나 실직 상태인 다...",이번 연수는 농업이 청년층의 취업 기회를 확대할 수 있는 실질적인 잠재력을 갖춘 핵...,Alternative for inorganic fertilizer: Youth ex...,A capacity building programme to expose young ...,The 62 participants were from diverse group of...,The training takes place on the back of the fa...,Daily Graphic,https://www.graphic.com.gh/news/general-news/a...,2023-12-30
3,가나,서아프리카,가나,수원국,농촌개발,"Zipline, 돼지 농장에 인공 수정을 위한 돼지 정액 배송",항공물류 배송업체인 Zipline과 가나 돼지 농업을 발전시키는 축산 사업인 Pip...,콜드체인 인큐베이터에 보관된 돼지 정액은 정확한 낙하 능력을 가진 드론에 의해 운반...,Zipline의 계획은 농업에서 효율성과 생산량을 증가시키기 위해 기술이 사용되는 ...,Zipline to Deliver Swine Semen to Pig Farms fo...,"Zipline, an aerial logistics delivery company ...","The swine semen, stored in cold-chain incubato...",Zipline’s initiative is seen as a part of the ...,Ghanaian Times,https://www.ghanaiantimes.com.gh/zipline-to-de...,2023-12-21
4,가나,서아프리카,가나,KOICA,교육,"한국국제협력단(KOICA), 가나 교육청에 100만 달러 교수학습 지원",한국국제협력단(KOICA)은 화요일에 가나 교육청(GES)에 100만 달러 이상에...,"KOICA 가나 사무소 이동현 소장은 교육 자료를 제공하면서 ""여성 STEM 프로젝...",Nkansah박사는 학생 중 12.5%가 각종 고등학교에서 과학 프로그램을 추구할 ...,"KOICA presents $1m teaching, learning aid to GES",The Korean Inter­national Coop­eration Agency ...,"The Country Director of KO­ICA Ghana, Mr Dongh...",He said about 12.5 per cent of students were a...,Ghanaian Times,https://www.ghanaiantimes.com.gh/koica-present...,2023-12-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,필리핀,동남아시아,필리핀,수원국,교육,"독해, 수학, 과학에서 필리핀 학생들이 여전히 최하위권 성적을 기록 중 - OECD...",OECD 국제학생평가프로그램에 참여한 다른 국가 학생들에 비해 필리핀 학생들의 평균...,"188개 학교 출신의 필리핀 학생 7,193명은 수학에서 평균 355점을 기록했으며...",2018년의 평가에서 기록한 필리핀 학생들의 저조한 학업성적은 교육부로 하여금 필리...,PH students still among lowest scorers in read...,There was no significant improvement in the av...,"The 7,193 Filipino students from 188 schools s...",The dismal performance of the Philippines in t...,Inquirer.net,https://newsinfo.inquirer.net/1871182/ph-stude...,2023-12-06
705,필리핀,동남아시아,필리핀,수원국,농촌개발,"마르코스, 아세안에 10개년 식량 안보 로드맵 수립 촉구",전 날 마르코스 대통령은 동남아시아국가연합 (ASEAN)과 일본에 기후 행동 및 농...,"마르코스 대통령은 도쿄에서 열린 일본-아세안 특별정상회담 세 번째 세션에서 ""식량 ...","""지속 가능한 에너지 안보는 저탄소 지역을 실현하고 기후 변화에 대응하기 위한 청정...",Marcos urges ASEAN: Craft 10-year food securit...,President Marcos yesterday urged the Associati...,“Inasmuch as food security is one of my admini...,“Sustainable energy security is a twin priorit...,Philstar,https://www.philstar.com/headlines/2023/12/18/...,2023-12-18
706,필리핀,동남아시아,필리핀,수원국,거버넌스평화,"BARMM, 24년 예산으로 98.4-B를 승인하고 2023년 사용하지 않은 자금에...","방사모로 의회는 수요일에 만장일치로 내년도 예산 984억 페소를 승인했으며, 자치 ...","재정·예산·관리위원회는 모든 부처, 기관, 사무실의 예산 제안을 철저히 조사해 다양...","2024년 예산에서는 교육에 여전히 302억 페소, 인프라에 177억 페소, 건강에...","BARMM okays 98.4-B ’24 budget, rushes reso on ...",The Bangsamoro Parliament on Wednesday unanimo...,"It said the Committee on Finance, Budget, and ...",It said the 2024 budget would “still prioritiz...,Business Mirror,https://businessmirror.com.ph/2023/12/28/barmm...,2023-12-28
707,필리핀,동남아시아,필리핀,수원국,기타,"세계은행, 2023년 필리핀 GDP 성장률 전망치 5.6%로 유지","세계은행은 필리핀 경제가 3분기에 성장 반등을 보인 후, 가계 및 정부 소비가 4분...",관광 부문의 회복과 IT-BPO 산업의 지속적인 성과로 인해 서비스가 성장을 주도할...,중기적으로 국내 수요의 개선으로 2024-2025년 평균 5.8%의 완만한 성장률 ...,World Bank keeps PHL 5.6% GDP growth projectio...,THE World Bank kept its 5.6-percent growth pro...,“Services are expected to drive growth due to ...,"Over the medium term, the December 2023 Philip...",Business Mirror,https://businessmirror.com.ph/2023/12/06/world...,2023-12-06
708,필리핀,동남아시아,필리핀,국제기구,기후행동,"아시아개발은행(ABD), 필리핀의 기후복원력 및 저탄소 이니셔티브 강화를 위해 2억...",ADB는 인프라 준비 및 혁신 시설(IPIF)에 대한 두번째 추가 자금인 이 대출이...,IPIF는 필리핀 정부가 주력 프로젝트로 선정한 복잡하고 중요한 기후 회복력 있는 ...,필리핀의 인프라 개발에 대한 ADB의 지원은 2018년 이후 꾸준히 증가하여 현재 ...,ADB okays $200-M loan to boost PHL’s climate r...,"ADB said the loan, the second additional finan...",The IPIF is used to support the preparation of...,ADB’s support for infrastructure development i...,Business Mirror,https://businessmirror.com.ph/2023/12/09/adb-o...,2023-12-09

## 2.  [참고]DRM 보안 적용된 Excel 파일 불러오기

### 2.1. pywin32 활용

In [ ]:
import pandas as pd
import win32com.client as win32
import os 

# Excel 실행
excel=win32.Dispatch('Excel.Application')   

# 경로 지정 및 파일 열기
filepath = os.getcwd() +'/data/test.xlsx'
wb = excel.Workbooks.Open(filepath)

# Sheet 지정
ws = wb.Worksheets(1) 

# 전체 행, 열 수 확인
nRow = ws.UsedRange.Rows.Count 
nColumn = ws.UsedRange.Columns.Count 

# 불러올 범위 지정
listValue = ws.Range(ws.Cells(1,1) , ws.Cells(nRow,nColumn)).Value
df_drm = pd.DataFrame(listValue[1:] , columns=listValue[0]) 

excel.Quit()     

df_drm

<br>
<br>

### 2.2. xlwings 라이브러리 활용

In [ ]:
# 라이브러리 설치
# !pip install xlwings

In [ ]:
# 라이브러리 불러오기
import xlwings as xw
import pandas as pd
import os

In [ ]:
# Excel 파일 열기
# filepath = os.getcwd() +'/data/test.xlsx'
book = xw.Book('./data/test.xlsx')

In [ ]:
# Sheet 선택
sheet = book.sheets[0]    

# 전체 데이터 데이터 불러오기
df_drm = sheet.used_range.options(pd.DataFrame, index = False).value
df_drm

In [ ]:
# 특정 부분만 불러오기
sheet = book.sheets[1]    
df_drm = sheet.range("A3:C5").options(pd.DataFrame, index = False).value
df_drm

In [ ]:
# 종료
xw.apps.active.quit()

#### End of script